# Generated by Django 3.0.5 on 2020-08-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultydata',
            name='email',
            field=models.EmailField(max_length=100, unique='True'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='email',
            field=models.EmailField(max_length=100, unique='True'),
        ),
    ]
