# Generated by Django 3.0.5 on 2020-09-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20200826_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectData',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=100)),
            ],
        ),
    ]
