# Generated by Django 3.0.5 on 2020-09-03 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_auto_20200903_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semesters',
            old_name='semester',
            new_name='sem',
        ),
    ]
