# Generated by Django 3.0.5 on 2020-09-04 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_auto_20200903_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance_master',
            fields=[
                ('att_id', models.AutoField(primary_key=True, serialize=False)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.FacultyData')),
                ('sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Semesters')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.StudentData')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Subjects')),
            ],
        ),
    ]
