# Generated by Django 3.0.5 on 2020-09-04 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_attendance_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance_master',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='attendance_master',
            name='sem',
        ),
    ]
