# Generated by Django 3.0.5 on 2020-09-05 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_auto_20200904_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='semesters',
            name='student',
        ),
        migrations.DeleteModel(
            name='attendance_master',
        ),
        migrations.DeleteModel(
            name='StudentData',
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
    ]
