# Generated by Django 3.0.5 on 2020-09-05 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_auto_20200905_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=100)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.FacultyData')),
            ],
        ),
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('std_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique='True')),
                ('password', models.CharField(max_length=100)),
                ('sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Semesters')),
            ],
        ),
        migrations.CreateModel(
            name='attendance_master',
            fields=[
                ('att_id', models.AutoField(primary_key=True, serialize=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.StudentData')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Subjects')),
            ],
        ),
    ]
