# Generated by Django 3.0.5 on 2020-09-05 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_attendance_master_studentdata_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semesters',
            name='sem',
            field=models.CharField(max_length=10, unique='True'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='sem',
            field=models.ForeignKey(db_column='sem', on_delete=django.db.models.deletion.CASCADE, to='attendance.Semesters', to_field='sem'),
        ),
    ]
