# Generated by Django 3.0.5 on 2020-09-05 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_auto_20200905_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='fill_attendance',
            fields=[
                ('std_att_id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(auto_now_add=True)),
                ('present', models.IntegerField()),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.attendance_master')),
            ],
        ),
    ]
