# Generated by Django 3.0.5 on 2020-09-05 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_auto_20200905_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance_table',
            fields=[
                ('att_id', models.AutoField(primary_key=True, serialize=False)),
                ('std_id', models.CharField(max_length=100, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.StudentData'))),
                ('sub_id', models.CharField(max_length=100, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Subjects'))),
                ('f_id', models.CharField(max_length=100, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.FacultyData'))),
            ],
        ),
    ]
