# Generated by Django 3.0.5 on 2020-09-05 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_attendance_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance_table',
            name='f_id',
        ),
    ]
