# Generated by Django 3.0.5 on 2020-09-05 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_remove_attendance_table_f_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance_Master_table',
            fields=[
                ('att_id', models.AutoField(primary_key=True, serialize=False)),
                ('sem_id', models.CharField(max_length=100, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Semesters'))),
                ('f_id', models.CharField(max_length=100, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.FacultyData'))),
                ('sub_id', models.CharField(max_length=100, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Subjects'))),
                ('std_id', models.CharField(max_length=100, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Semesters'))),
            ],
        ),
        migrations.DeleteModel(
            name='Attendance_table',
        ),
    ]
