# Generated by Django 3.0.5 on 2020-09-05 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0021_auto_20200905_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectTable',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=100)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.FacultyData')),
                ('sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Semesters')),
            ],
        ),
        migrations.AlterField(
            model_name='attendancetable',
            name='sub_id',
            field=models.CharField(max_length=100, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.SubjectTable')),
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
    ]
