# Generated by Django 3.0.5 on 2020-09-05 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0022_auto_20200905_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancetable',
            name='std_id',
            field=models.CharField(max_length=100, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.StudentData')),
        ),
    ]
