# Generated by Django 3.0.5 on 2020-09-05 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0023_auto_20200905_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancetable',
            name='std_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.StudentData'),
        ),
        migrations.AlterField(
            model_name='attendancetable',
            name='sub_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.SubjectTable'),
        ),
    ]
