# Generated by Django 3.0.5 on 2020-09-05 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0024_auto_20200905_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceMasterTable',
            fields=[
                ('att_id', models.AutoField(primary_key=True, serialize=False)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.FacultyData')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Semesters')),
                ('std_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.StudentData')),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.SubjectTable')),
            ],
        ),
        migrations.DeleteModel(
            name='AttendanceTable',
        ),
    ]
