# Generated by Django 3.0.5 on 2020-09-05 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0025_auto_20200905_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMasterData',
            fields=[
                ('std_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique='True')),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='subjecttable',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='subjecttable',
            name='sem',
        ),
        migrations.CreateModel(
            name='SubjectMasterTable',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=100)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.FacultyData')),
            ],
        ),
        migrations.AlterField(
            model_name='attendancemastertable',
            name='std_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.StudentMasterData'),
        ),
        migrations.AlterField(
            model_name='attendancemastertable',
            name='sub_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.SubjectMasterTable'),
        ),
        migrations.DeleteModel(
            name='StudentData',
        ),
        migrations.DeleteModel(
            name='SubjectTable',
        ),
    ]
