# Generated by Django 3.0.5 on 2020-09-05 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0026_auto_20200905_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('std_id', models.AutoField(primary_key=True, serialize=False)),
                ('Roll_no', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique='True')),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='attendancemastertable',
            name='std_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.StudentData'),
        ),
        migrations.DeleteModel(
            name='StudentMasterData',
        ),
    ]
