# Generated by Django 3.0.5 on 2020-09-05 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0028_auto_20200905_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancemastertable',
            name='faculty',
            field=models.CharField(max_length=10, null='True', verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.FacultyData')),
        ),
        migrations.AlterField(
            model_name='attendancemastertable',
            name='semester',
            field=models.CharField(max_length=10, null='True', verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Semesters')),
        ),
        migrations.AlterField(
            model_name='attendancemastertable',
            name='std_id',
            field=models.CharField(max_length=10, null='True', verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.StudentData')),
        ),
        migrations.AlterField(
            model_name='attendancemastertable',
            name='sub_id',
            field=models.CharField(max_length=10, null='True', verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.SubjectMasterTable')),
        ),
    ]
