# Generated by Django 3.0.5 on 2020-09-06 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0029_auto_20200905_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Data',
            fields=[
                ('std_id', models.AutoField(primary_key=True, serialize=False)),
                ('Roll_no', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=100, unique='True')),
                ('email', models.EmailField(max_length=100, unique='True')),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject_Table',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentData',
        ),
        migrations.AlterField(
            model_name='attendancemastertable',
            name='std_id',
            field=models.CharField(max_length=10, null='True', verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Student_Data')),
        ),
        migrations.AlterField(
            model_name='attendancemastertable',
            name='sub_id',
            field=models.CharField(max_length=10, null='True', verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Subject_Table')),
        ),
        migrations.DeleteModel(
            name='SubjectMasterTable',
        ),
    ]
