# Generated by Django 3.0.5 on 2020-09-06 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0030_auto_20200906_1803'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttendanceMasterTable',
            new_name='Attendance_Master_Table',
        ),
    ]
