# Generated by Django 3.0.5 on 2020-09-06 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0031_auto_20200906_1805'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance_Master_Table',
        ),
    ]
