# Generated by Django 3.0.5 on 2020-09-06 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0032_delete_attendance_master_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance_Master',
            fields=[
                ('att_id', models.AutoField(primary_key=True, serialize=False)),
                ('sem', models.CharField(max_length=5, null='True', verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Semesters'))),
                ('std', models.CharField(max_length=5, null='True', verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Student_Data'))),
                ('sub', models.CharField(max_length=5, null='True', verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Subject_Table'))),
                ('faculty', models.CharField(max_length=5, null='True', verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.FacultyData'))),
            ],
        ),
    ]
