# Generated by Django 3.0.5 on 2020-09-06 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0034_auto_20200906_1900'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance_Master',
        ),
    ]
