# Generated by Django 3.0.5 on 2020-09-06 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0036_attendance_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_attendance',
            fields=[
                ('std_att_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('att', models.CharField(max_length=3, null='True', verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Attendance_Master'))),
                ('present', models.CharField(max_length=3)),
            ],
            options={
                'unique_together': {('date', 'att')},
            },
        ),
    ]
