# Generated by Django 3.0.5 on 2020-09-06 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0037_student_attendance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance_master',
            unique_together={('sem', 'std', 'sub', 'faculty')},
        ),
    ]
