# Generated by Django 3.0.5 on 2020-09-06 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0038_auto_20200906_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject_table',
            name='faculty',
            field=models.CharField(max_length=5, null='True', verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.FacultyData')),
            preserve_default='True',
        ),
    ]
