# Generated by Django 3.0.5 on 2020-09-06 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0039_subject_table_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject_table',
            name='sem',
            field=models.CharField(max_length=5, null='True', verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Semesters')),
            preserve_default='True',
        ),
    ]
