# Generated by Django 3.0.5 on 2020-09-09 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0040_subject_table_sem'),
    ]

    operations = [
        migrations.CreateModel(
            name='complain_table',
            fields=[
                ('com_id', models.AutoField(primary_key=True, serialize=False)),
                ('com_msg', models.CharField(max_length=200)),
                ('std_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Student_Data')),
            ],
        ),
    ]
