# Generated by Django 3.0.5 on 2020-09-09 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0041_complain_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain_table',
            name='std_id',
            field=models.CharField(max_length=10, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Student_Data')),
        ),
    ]
