# Generated by Django 3.0.5 on 2020-09-09 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0042_auto_20200909_1645'),
    ]

    operations = [
        migrations.DeleteModel(
            name='complain_table',
        ),
    ]
