# Generated by Django 3.0.5 on 2020-09-09 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0043_delete_complain_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='complain_table',
            fields=[
                ('com_id', models.AutoField(primary_key=True, serialize=False)),
                ('std_id', models.CharField(max_length=10, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Student_Data'))),
                ('com_msg', models.CharField(max_length=200)),
            ],
        ),
    ]
