# Generated by Django 3.0.5 on 2020-09-09 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0045_auto_20200909_1705'),
    ]

    operations = [
        migrations.DeleteModel(
            name='complain_manage',
        ),
    ]
