# Generated by Django 3.0.5 on 2020-09-09 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0048_auto_20200909_1737'),
    ]

    operations = [
        migrations.DeleteModel(
            name='complaints',
        ),
    ]
