# Generated by Django 3.0.5 on 2020-09-09 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0049_delete_complaints'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaints',
            fields=[
                ('com_id', models.AutoField(primary_key=True, serialize=False)),
                ('std', models.CharField(max_length=10, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Student_Data'))),
                ('msg', models.CharField(max_length=250)),
            ],
        ),
    ]
