# Generated by Django 3.0.5 on 2020-09-09 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0050_complaints'),
    ]

    operations = [
        migrations.DeleteModel(
            name='complaints',
        ),
    ]
