# Generated by Django 3.0.5 on 2020-09-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0051_delete_complaints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_master',
            name='att_id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
