# Generated by Django 3.0.5 on 2020-09-23 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0053_complain_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attendance_master',
            table='Attendance_master',
        ),
        migrations.AlterModelTable(
            name='student_data',
            table='Student_master',
        ),
    ]
