# Generated by Django 3.0.5 on 2020-09-29 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0054_auto_20200923_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_data',
            name='s_sem',
            field=models.CharField(max_length=3, null=True, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Semesters')),
        ),
    ]
