# Generated by Django 3.0.5 on 2020-09-30 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0055_student_data_s_sem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student_attendance',
            unique_together=set(),
        ),
    ]
