# Generated by Django 3.0.5 on 2020-09-30 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0056_auto_20200930_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_Attendance_Sheet',
            fields=[
                ('std_att_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('att', models.CharField(max_length=3, null='True', verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Attendance_Master'))),
                ('present', models.CharField(max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='student_attendance',
        ),
    ]
