# Generated by Django 3.0.5 on 2020-10-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0057_auto_20200930_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='email',
            field=models.CharField(max_length=100, unique='True'),
        ),
    ]
