# Generated by Django 3.0.5 on 2020-10-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0058_auto_20201010_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='Roll_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
