# Generated by Django 3.0.5 on 2020-11-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0059_auto_20201011_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultydata',
            name='email',
            field=models.CharField(max_length=100, unique='True'),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='Roll_no',
            field=models.CharField(max_length=100),
        ),
    ]
