# Generated by Django 3.0.5 on 2020-12-01 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0060_auto_20201117_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='s_sem',
            field=models.CharField(default=1, max_length=3, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Semesters')),
            preserve_default=False,
        ),
    ]
