# Generated by Django 3.0.5 on 2020-12-01 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0061_auto_20201201_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='s_sem',
            field=models.CharField(max_length=10, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Semesters')),
        ),
    ]
